import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CE MOOC',
  description: 'Generated by MAOK-Yongsuk',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-[#1e3a8a] text-white p-6" >
          <div className="container mx-auto flex items-center justify-between">
            <Link href="/">
              <p className="text-2xl font-bold">CE-MOOC</p>
            </Link>
            <nav>
              <ul className="flex space-x-4">
                <li>
                  <Link href="/register">
                    <p className="text-lg">Register</p>
                  </Link>
                </li>
                <li>
                  <Link href="/login">
                    <p className="text-lg">Login</p>
                  </Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <main className="flex-grow">
          <div className="container mx-auto">{children}</div>
        </main>
        <footer className="bg-[#1e3a8a] text-white text-center py-10 mt-4">
          <div className="container mx-auto">
            <p>&copy; 2023 CE-MOOC. All rights reserved.</p>
          </div>
        </footer>

      </body>
    </html>
  )
}
